name: Claude Review Mode

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  code-review:
    # Run on PR events, or when someone comments "@claude review" on a PR
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude review'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      # Note: No id-token needed for review mode!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better diff analysis

      - name: Code Review with Claude
        uses: anthropics/claude-code-action@km/add-review-mode
        with:
          mode: review
          # No anthropic_api_key needed - uses default GitHub token
          # No github_token needed - uses default GITHUB_TOKEN
          timeout_minutes: "30"
          custom_instructions: |
            Focus on:
            - Code quality and maintainability
            - Security vulnerabilities
            - Performance issues
            - Best practices and design patterns
            - Test coverage gaps
            
            Be constructive and provide specific suggestions for improvements.
            Use GitHub's suggestion format when proposing code changes.